#!/usr/bin/env bash

# Make the sing-box service survive network transitions on a laptop / hotspot.
#
# Root cause this addresses: sing-box uses auto_detect_interface to bind its
# outbounds to the uplink. When the uplink appears late at boot, drops, or the
# machine roams between networks, sing-box gets stuck on "missing default
# interface" and every connection (including DNS) times out -- yet the process
# never exits, so systemd's Restart=on-failure does not help. The proxy is dead
# until something restarts it.
#
# This installs two complementary self-healing mechanisms:
#   A. A NetworkManager dispatcher hook that restarts sing-box whenever a real
#      (non-tun) interface comes up or connectivity changes -- fixes "started
#      before WiFi" and "switched networks" at the source.
#   B. A systemd timer that periodically probes the proxy and restarts sing-box
#      if it has soft-died -- backstop for silent mid-session drops that fire no
#      NetworkManager event.
#
# Idempotent: safe to re-run; it overwrites its own files. Use --remove to undo.

set -euo pipefail

SERVICE_NAME="sing-box"
TUN_DEV="singbox"
WATCHDOG_NAME="sing-box-watchdog"
INTERVAL="2min"
DEBOUNCE="20"
ACTION="install"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HEALTHCHECK_SCRIPT="${SCRIPT_DIR}/sing_box_healthcheck.sh"
DISPATCHER_DIR="/etc/NetworkManager/dispatcher.d"

usage() {
  cat <<'EOF'
Usage:
  sudo ./sing_box/Script/setup_resilience.sh [options]
  sudo ./sing_box/Script/setup_resilience.sh --remove [options]

Installs self-healing for sing-box across network transitions:
  A. NetworkManager dispatcher hook -> restart on uplink up / connectivity change
  B. systemd watchdog timer        -> restart on detected soft-death

Options:
  -n, --name <service>     sing-box service name, default: sing-box
      --tun-dev <name>     tun device to ignore in uplink checks, default: singbox
      --interval <dur>     watchdog probe interval (OnUnitActiveSec), default: 2min
      --debounce <secs>    min seconds between dispatcher-triggered restarts,
                           default: 20
      --remove             Remove the dispatcher hook, watchdog timer/service
  -h, --help               Show help

Examples:
  sudo ./sing_box/Script/setup_resilience.sh
  sudo ./sing_box/Script/setup_resilience.sh --interval 90s
  sudo ./sing_box/Script/setup_resilience.sh --remove
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -n|--name)     SERVICE_NAME="${2:-}"; shift 2 ;;
    --tun-dev)     TUN_DEV="${2:-}"; shift 2 ;;
    --interval)    INTERVAL="${2:-}"; shift 2 ;;
    --debounce)    DEBOUNCE="${2:-}"; shift 2 ;;
    --remove)      ACTION="remove"; shift ;;
    -h|--help)     usage; exit 0 ;;
    *)
      echo "Error: unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ ${EUID} -ne 0 ]]; then
  echo "Error: please run as root, for example: sudo ./sing_box/Script/setup_resilience.sh" >&2
  exit 1
fi

if [[ -z "${SERVICE_NAME}" ]]; then
  echo "Error: service name cannot be empty" >&2
  exit 1
fi

if ! command -v systemctl >/dev/null 2>&1; then
  echo "Error: systemctl is required" >&2
  exit 1
fi

DISPATCHER_FILE="${DISPATCHER_DIR}/90-${SERVICE_NAME}-restart"
WATCHDOG_SERVICE_FILE="/etc/systemd/system/${WATCHDOG_NAME}.service"
WATCHDOG_TIMER_FILE="/etc/systemd/system/${WATCHDOG_NAME}.timer"

remove_all() {
  local removed="no"

  if [[ -f "${DISPATCHER_FILE}" ]]; then
    rm -f "${DISPATCHER_FILE}"
    echo "Removed dispatcher hook: ${DISPATCHER_FILE}"
    removed="yes"
  fi

  systemctl stop "${WATCHDOG_NAME}.timer" >/dev/null 2>&1 || true
  systemctl disable "${WATCHDOG_NAME}.timer" >/dev/null 2>&1 || true
  systemctl stop "${WATCHDOG_NAME}.service" >/dev/null 2>&1 || true
  if [[ -f "${WATCHDOG_TIMER_FILE}" ]]; then
    rm -f "${WATCHDOG_TIMER_FILE}"
    echo "Removed timer file: ${WATCHDOG_TIMER_FILE}"
    removed="yes"
  fi
  if [[ -f "${WATCHDOG_SERVICE_FILE}" ]]; then
    rm -f "${WATCHDOG_SERVICE_FILE}"
    echo "Removed service file: ${WATCHDOG_SERVICE_FILE}"
    removed="yes"
  fi

  systemctl daemon-reload
  systemctl reset-failed "${WATCHDOG_NAME}.service" >/dev/null 2>&1 || true
  systemctl reset-failed "${WATCHDOG_NAME}.timer" >/dev/null 2>&1 || true

  if [[ "${removed}" == "no" ]]; then
    echo "Nothing to remove for: ${SERVICE_NAME}"
  else
    echo "Resilience hooks removed for: ${SERVICE_NAME}"
  fi
}

if [[ "${ACTION}" == "remove" ]]; then
  remove_all
  exit 0
fi

if [[ ! -f "${HEALTHCHECK_SCRIPT}" ]]; then
  echo "Error: health-check script not found: ${HEALTHCHECK_SCRIPT}" >&2
  exit 1
fi
chmod +x "${HEALTHCHECK_SCRIPT}"

# --- A. NetworkManager dispatcher hook -------------------------------------
if [[ -d "${DISPATCHER_DIR}" ]]; then
  cat > "${DISPATCHER_FILE}" <<EOF
#!/usr/bin/env bash
# Auto-generated by setup_resilience.sh. Restart ${SERVICE_NAME} when a real
# uplink comes up or connectivity changes, so auto_detect_interface re-binds to
# the new interface. Ignores the sing-box tun device to avoid restart loops, and
# debounces bursts of events.
interface="\$1"
action="\$2"

# Never react to our own tun device coming up after a restart.
[ "\${interface}" = "${TUN_DEV}" ] && exit 0

case "\${action}" in
  up|connectivity-change|dhcp4-change|dhcp6-change) ;;
  *) exit 0 ;;
esac

# Only act if the service is supposed to be running.
systemctl is-active --quiet "${SERVICE_NAME}.service" || exit 0

# Debounce: collapse bursts of events into a single restart.
stamp="/run/${SERVICE_NAME}-dispatcher.last"
now="\$(date +%s)"
if [ -f "\${stamp}" ]; then
  last="\$(cat "\${stamp}" 2>/dev/null || echo 0)"
  [ "\$(( now - last ))" -lt ${DEBOUNCE} ] && exit 0
fi
echo "\${now}" > "\${stamp}"

# --no-block: never hold up the NetworkManager dispatcher.
systemctl restart --no-block "${SERVICE_NAME}.service"
exit 0
EOF
  chown root:root "${DISPATCHER_FILE}"
  chmod 0755 "${DISPATCHER_FILE}"
  echo "Installed dispatcher hook: ${DISPATCHER_FILE}"
else
  echo "Warning: ${DISPATCHER_DIR} not found; skipping NetworkManager hook (B watchdog still covers it)."
fi

# --- B. systemd watchdog timer ---------------------------------------------
cat > "${WATCHDOG_SERVICE_FILE}" <<EOF
[Unit]
Description=Probe ${SERVICE_NAME} and restart it if it has soft-died (${WATCHDOG_NAME})
After=${SERVICE_NAME}.service

[Service]
Type=oneshot
Environment=SERVICE_NAME=${SERVICE_NAME}
Environment=TUN_DEV=${TUN_DEV}
ExecStart=${HEALTHCHECK_SCRIPT}
EOF
echo "Wrote service file: ${WATCHDOG_SERVICE_FILE}"

cat > "${WATCHDOG_TIMER_FILE}" <<EOF
[Unit]
Description=Run ${WATCHDOG_NAME}.service every ${INTERVAL}

[Timer]
OnBootSec=2min
OnUnitActiveSec=${INTERVAL}
Unit=${WATCHDOG_NAME}.service

[Install]
WantedBy=timers.target
EOF
echo "Wrote timer file: ${WATCHDOG_TIMER_FILE}"

systemctl daemon-reload
systemctl enable --now "${WATCHDOG_NAME}.timer"
echo "Watchdog enabled: ${WATCHDOG_NAME}.timer"

echo ""
echo "Self-healing installed for: ${SERVICE_NAME}"
echo "  A. ${DISPATCHER_FILE}"
echo "  B. ${WATCHDOG_NAME}.timer (every ${INTERVAL})"
echo ""
echo "Next watchdog run:"
systemctl list-timers --no-pager "${WATCHDOG_NAME}.timer" | sed -n '1,3p'
echo ""
echo "Probe once now:    sudo systemctl start ${WATCHDOG_NAME}.service"
echo "Follow logs:       journalctl -u ${WATCHDOG_NAME}.service -f"
